---
# tasks file for rhv-ocp

#- include_vars: ovirt_password.yml

#- name: Obtain SSO token with using username/password credentials
#  ovirt_auth:
#    url: https://rhvm.rhv.homelab.work/ovirt-engine/api/v3
#    username: admin@internal
#    ca_file: ca.crt
#    password: "{{ ovirt_password }}"

# Verify expected DNS and store associated IPs
- name: Validate and store OpenShift Master IPs
  command: "dig +short {{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.masters.count }}
  when: cloud_infrastructure.masters.count > 0
  register: masters_ip


- name: Validate and store OpenShift Etcd IPs
  command: "dig +short {{ cloud_infrastructure.etcdnodes.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.etcdnodes.count }}
  when: cloud_infrastructure.etcdnodes.count > 0
  register: etcdnodes_ip

- name: Validate and store OpenShift Infra IPs
  command: "dig +short {{ cloud_infrastructure.infranodes.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.infranodes.count }}
  when: cloud_infrastructure.infranodes.count > 0
  register: infranodes_ip

- name: Validate and store OpenShift App Nodes IPs
  command: "dig +short {{ cloud_infrastructure.appnodes.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.appnodes.count }}
  when: cloud_infrastructure.appnodes.count > 0
  register: appnodes_ip

- name: Validate and store OpenShift CNS Nodes IPs
  command: "dig +short {{ cloud_infrastructure.cnsnodes.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.cnsnodes.count }}
  when: cloud_infrastructure.cnsnodes.count > 0
  register: cnsnodes_ip

## Create the VMs
- name: Obtain SSO token
  ovirt_auth:
    state: present
#    url: "{{ ovirt_url }}"
#    username: "{{ ovirt_username }}"
#    password: "{{ ovirt_password }}"
#    ca_file: "{{ ovirt_ca_file }}"

### Creates the Masters
- name: Create OCP Master Virtual Machines from template
  ovirt_vms:
    state: running
    name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
    template: "{{ cloud_infrastructure.masters.flavor }}"
    cluster: "{{ cloud_infrastructure.masters.rhv_cluster }}"
    wait: True
    storage_domain: "{{ cloud_infrastructure.masters.docker_storage_domain }}"
    cloud_init:
      host_name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
      dns_search: "{{ dns_domain }}"
      nic_boot_protocol: static
      nic_ip_address: "{{ masters_ip[item].stdout }}"
      nic_netmask: "{{ cloud_infrastructure.masters.network_netmask }}"
      nic_gateway: "{{ cloud_infrastructure.masters.network_gateway }}"
      nic_name: "{{ cloud_infrastructure.masters.network_nic_name }}"
      nic_on_boot: true
  with_sequence: count={{ cloud_infrastructure.masters.count }}

- name: Create OCP Master Docker disk
  ovirt_disks:
    name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}-{{ env_id }}-docker-disk"
    vm_name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
    storage_domain: "{{ cloud_infrastructure.masters.docker_storage_domain }}"
    size: "{{ cloud_infrastructure.masters.docker_volume_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ cloud_infrastructure.masters.count }}

- name: Create OCP Master Etcd disk
  ovirt_disks:
    name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}-{{ env_id }}-etcd-disk"
    vm_name: "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
    storage_domain: "{{ storage_domain }}"
    size: "{{ cloud_infrastructure.masters.etcd_volume_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ cloud_infrastructure.masters.count }}

- name: Tag as rhv-ocp host
  ovirt_tags:
    name: rhv-ocp
    state: attached
    vms:
      - "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.masters.count }}

- name: Tag the masters
  ovirt_tags:
    name: rhv-ocp-master
    state: attached
    vms:
      - "{{ cloud_infrastructure.masters.name_prefix }}-{{ item }}.{{ env_id }}.{{ dns_domain }}"
  with_sequence: count={{ cloud_infrastructure.masters.count }}

########### INFRA NODES ##############

- name: Creates OCP Infra Virtual Machine from template
  ovirt_vms:
    state: running
    name: "{{ infra_name }}-{{ item }}"
    template: "{{ rhv_template }}"
    cluster: Default
    cpu_cores: "{{ infra_cpu_cores }}"
    memory: "{{ infra_memory }}"
    wait: true
    storage_domain: "{{ storage_domain }}"
    cloud_init:
      host_name: "{{ infra_name }}-{{ item }}.{{ domain_name }}"
      dns_search: homelab.work
      nic_boot_protocol: static
      nic_ip_address: 192.168.2.222
      nic_netmask: 255.255.255.0
      nic_gateway: 192.168.2.1
      nic_name: eth0
      nic_on_boot: true
      custom_script: |
        runcmd:
         - [ ipa-client-install, -U, --password, {{ ipa_password }}, --realm, HOMELAB.WORK, -p, {{ ipa_user }}, --mkhomedir, --enable-dns-updates, --hostname={{ infra_name }}-{{ item }}.{{ domain_name }}, --domain={{ domain_name }}, --force-join ]
  with_sequence: count={{ infra_count }}

- name: Create OCP Infra Docker disk
  ovirt_disks:
    name: "{{ infra_name }}-{{ item }}-docker-disk"
    vm_name: "{{ infra_name }}-{{ item }}"
    storage_domain: "{{ storage_domain }}"
    size: "{{ infra_docker_disk_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ infra_count }}

- name: Create OCP Infra Origin disk
  ovirt_disks:
    name: "{{ infra_name }}-{{ item }}-origin-disk"
    vm_name: "{{ infra_name }}-{{ item }}"
    storage_domain: "{{ storage_domain }}"
    size: "{{ infra_origin_disk_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ infra_count }}

- name: Tag as rhv-ocp host
  ovirt_tags:
    name: rhv-ocp
    state: attached
    vms:
      - "{{ infra_name }}-{{ item }}"
  with_sequence: count={{ infra_count }}

- name: Tag the infra nodes
  ovirt_tags:
    name: rhv-ocp-infra
    state: attached
    vms:
      - "{{ infra_name }}-{{ item }}"
  with_sequence: count={{ infra_count }}

########### APP NODES ##############

- name: Creates OCP App Nodes Virtual Machine from template
  ovirt_vms:
    state: running
    name: "{{ appnode_name }}-{{ item }}"
    template: "{{ rhv_template }}"
    cluster: Default
    cpu_cores: "{{ appnode_cpu_cores }}"
    memory: "{{ appnode_memory }}"
    wait: true
    storage_domain: "{{ storage_domain }}"
    cloud_init:
      host_name: "{{ appnode_name }}-{{ item }}.{{ domain_name }}"
      dns_search: homelab.work
      nic_boot_protocol: static
      nic_ip_address: 192.168.2.223
      nic_netmask: 255.255.255.0
      nic_gateway: 192.168.2.1
      nic_name: eth0
      nic_on_boot: true
      custom_script: |
        runcmd:
         - [ ipa-client-install, -U, --password, {{ ipa_password }}, --realm, HOMELAB.WORK, -p, {{ ipa_user }}, --mkhomedir, --enable-dns-updates, --hostname={{ appnode_name }}-{{ item }}.{{ domain_name }}, --domain={{ domain_name }}, --force-join ]
  with_sequence: count={{ appnode_count }}

- name: Create OCP App Node Docker disk
  ovirt_disks:
    name: "{{ appnode_name }}-{{ item }}-docker-disk"
    vm_name: "{{ appnode_name }}-{{ item }}"
    storage_domain: "{{ storage_domain }}"
    size: "{{ appnode_docker_disk_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ appnode_count }}

- name: Create OCP App Node Origin disk
  ovirt_disks:
    name: "{{ appnode_name }}-{{ item }}-origin-disk"
    vm_name: "{{ appnode_name }}-{{ item }}"
    storage_domain: "{{ storage_domain }}"
    size: "{{ appnode_origin_disk_size }}"
    format: cow
    interface: virtio
  with_sequence: count={{ appnode_count }}

- name: Tag as rhv-ocp host
  ovirt_tags:
    name: rhv-ocp
    state: attached
    vms:
      - "{{ appnode_name }}-{{ item }}"
  with_sequence: count={{ appnode_count }}

- name: Tag the infra nodes
  ovirt_tags:
    name: rhv-ocp-appnode
    state: attached
    vms:
      - "{{ appnode_name }}-{{ item }}"
  with_sequence: count={{ appnode_count }}

## Reboot all the nodes to clear run-once

#- name: Pause for 2 minutes to ensure that cloud-init has finished
#  pause:
#    minutes: 2

#- name: Power off OCP Ansible Host
#  ovirt_vms:
#    state: stopped
#    name: "{{ ansible_bastion_name }}"

#- name: Power on OCP Ansible Host
#  ovirt_vms:
#    state: running
#    name: "{{ ansible_bastion_name }}"
#    cluster: Default

#- name: Stop OCP masters Virtual Machines
#  ovirt_vms:
#    state: stopped
#    name: "{{ master_name }}-{{ item }}"
#  with_sequence: count={{ master_count }}

#- name: Start OCP masters Virtual Machines
#  ovirt_vms:
#    state: running
#    name: "{{ master_name }}-{{ item }}"
#  with_sequence: count={{ master_count }}

#- name: Stop OCP Infra Virtual Machines
#  ovirt_vms:
#    state: stopped
#    name: "{{ infra_name }}-{{ item }}"
#  with_sequence: count={{ infra_count }}

#- name: Start OCP Infra Virtual Machines
#  ovirt_vms:
#    state: running
#    name: "{{ infra_name }}-{{ item }}"
#  with_sequence: count={{ infra_count }}

#- name: Start OCP App Node Virtual Machines
#  ovirt_vms:
#    state: stopped
#    name: "{{ appnode_name }}-{{ item }}"
#  with_sequence: count={{ appnode_count }}

#- name: Start OCP App Node Virtual Machines
#  ovirt_vms:
#    state: running
#    name: "{{ appnode_name }}-{{ item }}"
#  with_sequence: count={{ appnode_count }}
